
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  graphql:
    playground:
      mapping: /playground
      endpoint: /graphql
      subscriptionEndpoint: /subscriptions
      staticPath.base: my-playground-resources-folder
      enabled: true
      pageTitle: Playground

server:
  port: 3001
